# Generated by Django 5.2.7 on 2025-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsmodel_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='measurement',
            field=models.CharField(choices=[('GR', 'Gram'), ('PC', 'Piece'), ('L', 'Litre')], default='GR'),
        ),
    ]
