# Generated by Django 5.2.7 on 2025-11-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='custom_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cartlist',
            name='color',
            field=models.CharField(default='#ffffff', max_length=15),
        ),
    ]
