# Generated by Django 5.2.7 on 2025-10-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='used',
        ),
    ]
