# Generated by Django 5.2.7 on 2025-11-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipemodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='image',
        ),
    ]
