# Generated by Django 5.2.7 on 2025-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
